import torch
import numpy as np
import os
import json
import pandas as pd
from transformers import (
    AutoTokenizer, 
    AutoModelForSequenceClassification, 
    Trainer, 
    TrainingArguments,
    # Se eliminan SaveStrategy e IntervalStrategy de aquí
)
# === FIX CLAVE: Importar las estrategias desde el módulo interno ===
from transformers.trainer_utils import IntervalStrategy, SaveStrategy
# ==================================================================

from datasets import Dataset 
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
from typing import Dict, Any, Tuple

# --- CONFIGURACIÓN GENERAL ---
MODEL_DIR = "roberta_ai_model" 
MODEL_ID_HF_BASE = "dccuchile/bert-base-spanish-wwm-uncased" 
TRAIN_FILE = os.path.join('pan-25-ai-detection', 'train.jsonl')
DEV_FILE = os.path.join('pan-25-ai-detection', 'dev.jsonl')
MAX_LENGTH = 512 


LABELS = [
    "Completamente escrito por humanos",
    "Iniciado por humanos, continuado por máquina",
    "Escrito por humanos, pulido por máquina",
    "Escrito por máquina, luego humanizado por máquina",
    "Escrito por máquina, luego editado por humanos",
    "Texto profundamente mezclado"
]
NUM_LABELS = len(LABELS)

# Mapeos necesarios para el entrenamiento y la carga del modelo
LABEL_TO_ID = {label: i for i, label in enumerate(LABELS)}
ID_TO_LABEL = {id: label for label, id in LABEL_TO_ID.items()}

# === Mapeo de Etiquetas en Inglés a Etiquetas en Español ===
ENGLISH_TO_SPANISH_MAP = {
    "fully human-written": "Completamente escrito por humanos",
    "human-initiated, then machine-continued": "Iniciado por humanos, continuado por máquina",
    "human-written, then machine-polished": "Escrito por humanos, pulido por máquina",
    "machine-written, then human-edited": "Escrito por máquina, luego editado por humanos",
    "machine-written, then machine-humanized": "Escrito por máquina, luego humanizado por máquina", 
    "deeply-mixed text; where some parts are written by a human and some are generated by a machine": "Texto profundamente mezclado",
    "fully machine-generated": "Escrito por máquina, luego humanizado por máquina", 
    "human-written, machine-polished": "Escrito por humanos, pulido por máquina", 
    "machine-written, human-edited": "Escrito por máquina, luego editado por humanos", 
}

IA_WEIGHTS = [0.0, 0.5, 0.4, 0.8, 0.6, 1.0] 


# --- FUNCIONES DE CARGA Y ENTRENAMIENTO ---

def get_label_id(label_key: Any) -> int | None:
    if isinstance(label_key, int) and 0 <= label_key < NUM_LABELS:
        return label_key
    if isinstance(label_key, str):
        if label_key in LABEL_TO_ID:
            return LABEL_TO_ID[label_key]
        if label_key in ENGLISH_TO_SPANISH_MAP:
            spanish_label = ENGLISH_TO_SPANISH_MAP[label_key]
            return LABEL_TO_ID.get(spanish_label)
    return None

def load_data(file_path: str) -> pd.DataFrame | None:
    data = []
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            for line in f:
                item = json.loads(line.strip())
                text_content = item.get('text')
                label_key = item.get('label_text') or item.get('label')
                label_id = get_label_id(label_key)

                if text_content and label_id is not None:
                    data.append({'text': text_content, 'label_id': label_id}) 
                elif label_key is not None:
                    print(f"AVISO: Etiqueta desconocida/inválida '{label_key}' en {file_path}. Fila saltada.")
                
    except FileNotFoundError:
        print(f"ERROR: Archivo no encontrado: {file_path}. No se puede entrenar.")
        return None
    
    return pd.DataFrame(data)

def tokenize_function(examples: Dict[str, Any]) -> Dict[str, Any]:
    return tokenizer(examples['text'], truncation=True, padding="max_length", max_length=MAX_LENGTH)

def compute_metrics(p) -> Dict[str, float]:
    predictions = np.argmax(p.predictions, axis=1)
    
    accuracy = accuracy_score(p.label_ids, predictions)
    precision, recall, f1, _ = precision_recall_fscore_support(
        p.label_ids, 
        predictions, 
        average='weighted', 
        labels=np.arange(NUM_LABELS)
    )
    
    return {'accuracy': accuracy, 'f1': f1, 'precision': precision, 'recall': recall}


def train_and_save_roberta() -> Tuple[AutoModelForSequenceClassification | None, AutoTokenizer | None]:
    """Descarga el modelo base, realiza el fine-tuning y guarda el resultado."""
    print("\n\n" + "="*50)
    print("🚀 INICIANDO PROCESO DE FINE-TUNING (BERT/RoBERTa para Español) 🚀")
    print("="*50)

    train_df = load_data(TRAIN_FILE)
    dev_df = load_data(DEV_FILE)
    
    if train_df is None or dev_df is None or train_df.empty or dev_df.empty:
        print("ERROR: No se pudieron cargar datos válidos. Saliendo del entrenamiento.")
        return None, None

    train_df = train_df.rename(columns={'label_id': 'labels'}).reset_index(drop=True)
    dev_df = dev_df.rename(columns={'label_id': 'labels'}).reset_index(drop=True)

    train_dataset = Dataset.from_pandas(train_df)
    dev_dataset = Dataset.from_pandas(dev_df)
    
    tokenized_train_dataset = train_dataset.map(tokenize_function, batched=True)
    tokenized_dev_dataset = dev_dataset.map(tokenize_function, batched=True)
    
    tokenized_train_dataset = tokenized_train_dataset.remove_columns(['text'])
    tokenized_dev_dataset = tokenized_dev_dataset.remove_columns(['text'])
    
    model_ft = AutoModelForSequenceClassification.from_pretrained(
        MODEL_ID_HF_BASE, 
        num_labels=NUM_LABELS,
        id2label=ID_TO_LABEL,
        label2id=LABEL_TO_ID
    )

    # === FIX FINAL: Eliminamos los argumentos incompatibles con versiones antiguas ===
    # El modelo se entrenará, pero solo guardará el último checkpoint.
    training_args = TrainingArguments(
        output_dir='./roberta_results_temp', 
        num_train_epochs=3,
        per_device_train_batch_size=8,
        per_device_eval_batch_size=8,
        weight_decay=0.01,
        logging_dir='./roberta_logs',                           
        
        # === SE REMUEVEN LOS ARGUMENTOS CONFLICTIVOS (TypeError) ===
        # evaluation_strategy="epoch", 
        # save_strategy="epoch",      
        # load_best_model_at_end=True,
        # metric_for_best_model='f1',
        # greater_is_better=True,
        # ==========================================================
        
        # Solo dejamos argumentos base que son universales
        save_total_limit=1,
    )

    trainer = Trainer(
        model=model_ft,
        args=training_args,
        train_dataset=tokenized_train_dataset,
        eval_dataset=tokenized_dev_dataset,
        tokenizer=tokenizer,
        compute_metrics=compute_metrics,
    )

    trainer.train()

    print(f"\n💾 Guardando modelo fine-tuneado en la carpeta: {MODEL_DIR}")
    if not os.path.exists(MODEL_DIR):
        os.makedirs(MODEL_DIR)
        
    trainer.save_model(MODEL_DIR)
    tokenizer.save_pretrained(MODEL_DIR)
    print("✅ ¡Fine-Tuning completado y modelo guardado!")
    print("="*50 + "\n\n")
    
    return model_ft, tokenizer


# --- FUNCIÓN PRINCIPAL DE PREDICCIÓN (API) ---

def estimate_tone(text, probs):
    text_lower = text.lower()
    if any(word in text_lower for word in ["por lo tanto", "en conclusión", "considerando", "de acuerdo con"]):
        return "Formal / académico"
    elif any(word in text_lower for word in ["feliz", "triste", "emocionado", "enojado", "sorprendido"]):
        return "Emocional / expresivo"
    elif any(word in text_lower for word in ["algoritmo", "modelo", "red neuronal", "parámetro", "datos"]):
        return "Técnico / analítico"
    elif probs[0] > 0.5:
        return "Natural / humano"
    elif probs[-1] > 0.5:
        return "Artificial / mecanizado"
    else:
        return "Neutro"


def get_text_stats(document_content: str) -> Dict[str, int]:
    characters = len(document_content)
    words = len(document_content.split())
    sentences = document_content.count('.') + document_content.count('!') + document_content.count('?')
    return {"characters": characters, "words": words, "sentences": sentences}


def predict_ai_content(document_content: str) -> Dict[str, Any]:
    if model is None or tokenizer is None:
        raise RuntimeError("El modelo RoBERTa no fue cargado correctamente.")

    inputs = tokenizer(
        document_content,
        return_tensors="pt",
        truncation=True,
        padding=True,
        max_length=MAX_LENGTH
    ).to(device)

    with torch.no_grad():
        outputs = model(**inputs)
        probs = torch.nn.functional.softmax(outputs.logits, dim=-1).cpu().numpy()[0]

    label_idx = int(np.argmax(probs))
    label_text = LABELS[label_idx]
    ai_score = float(sum(p * w for p, w in zip(probs, IA_WEIGHTS)) * 100)
    tone = estimate_tone(document_content, probs)

    return {"label": label_text, "ai_score": ai_score, "tone": tone}


# --- CARGA GLOBAL DEL MODELO (EJECUCIÓN PRINCIPAL) ---

model = None
tokenizer = None
device = "cuda" if torch.cuda.is_available() else "cpu"


try:
    # 1. Intentamos cargar el modelo fine-tuneado localmente
    print("🔹 Intentando cargar modelo fine-tuneado de la carpeta local...")
    # La clave para evitar el error 401/OSError es local_files_only=True
    tokenizer = AutoTokenizer.from_pretrained(MODEL_DIR, local_files_only=True) 
    model = AutoModelForSequenceClassification.from_pretrained(MODEL_DIR, local_files_only=True).to(device)
    print(f"✅ Modelo local fine-tuneado cargado y listo en {device.upper()}.")

except OSError:
    # 2. Si falla (carpeta no existe), simplemente cargamos el modelo base para que la aplicación NO se caiga.
    print(f"⚠️ Modelo no encontrado en '{MODEL_DIR}'. Saltando entrenamiento (no hay GPU).")
    print(f"Cargando modelo base '{MODEL_ID_HF_BASE}'. ¡Las predicciones NO serán precisas!")
    
    # Cargamos el tokenizer base
    tokenizer = AutoTokenizer.from_pretrained(MODEL_ID_HF_BASE)
    
    # Configuramos el modelo base con las 6 etiquetas
    model = AutoModelForSequenceClassification.from_pretrained(
        MODEL_ID_HF_BASE, 
        num_labels=NUM_LABELS,
        id2label=ID_TO_LABEL,
        label2id=LABEL_TO_ID
    ).to(device)
    
    # El entrenamiento está deshabilitado.
    
if model is not None:
    model.eval()
    print(f"✅ Detector de IA (RoBERTa/BERT) completamente inicializado.")


 # --- VERSIÓN CON ENTRENAMIENTO (REQUIERE GPU) ---

 
#     except OSError:
#     # 2. Si falla (carpeta no existe), descargamos el modelo base para el tokenizer y entrenamos
#     print(f"⚠️ Modelo no encontrado en '{MODEL_DIR}'. Iniciando proceso de entrenamiento.")
    
#     # Cargamos el tokenizer base de la versión estable
#     tokenizer = AutoTokenizer.from_pretrained(MODEL_ID_HF_BASE)
    
#     # Entrenar y guardar el modelo fine-tuneado
#     model_ft, tokenizer_ft = train_and_save_roberta()
    
#     if model_ft is not None:
#         model = model_ft
#         tokenizer = tokenizer_ft
#         print(f"✅ Modelo fine-tuneado cargado con éxito después del entrenamiento en {device.upper()}.")
#     else:
#         print("❌ ERROR FATAL: El entrenamiento no pudo completarse. El detector de IA está inactivo.")


# if model is not None:
#     model.eval()
#     print(f"✅ Detector de IA (RoBERTa/BERT) completamente inicializado.")